# Generated by Django 2.2.8 on 2020-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('met', models.DateField()),
            ],
            options={
                'verbose_name_plural': 'people',
                'db_table': 'people',
                'ordering': ['last_name'],
            },
        ),
    ]
