# Generated by Django 2.2.8 on 2020-01-10 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('level', models.IntegerField(choices=[(1, 'Text'), (2, 'Voice'), (3, 'In Person')])),
                ('description', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.Person')),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['date'],
            },
        ),
    ]
