# Generated by Django 2.2.8 on 2020-02-02 14:44

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='person',
            table='old_people',
        ),
    ]
