# Generated by Django 2.2.8 on 2020-01-15 13:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=core.models.create_filename),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
